run DAY DEBUG:
    cd day{{DAY}} && go run main.go {{DEBUG}} -- input.txt

test DAY DEBUG:
    cd day{{DAY}} && go run main.go {{DEBUG}} -- test_input.txt


new DAY:
    cp -r template day{{DAY}}

submit DAY:
    OUTPUT=$(just --justfile justfile run "$DAY") 
    submit.sh {{DAY}}
